### ISSUE TITLE
Version 0.0.20 not working on Windows

### ISSUE THREAD

**Issue by martinstz** [elgatito/script.elementum.burst#64] opened 2018-07-31 12:32 UTC
Hi!
After update to v.0.0.20 Elementum Burst stop working on Windows OS. I install win_inet_pton on Python 2.7, but nothings happens. And after update, Zamunda and Zelka cannot find anything on other OS where addon working. In old version 0.0.19 everything worked fine.
Thanks in advance!

**Comment by elgatito** [comment] 2018-07-31 12:33
duplicate of #63

**Closed by elgatito** 2018-07-31 12:33 UTC
