### ISSUE TITLE
Adding TNTVillage

### ISSUE THREAD

**Issue by kalika303** [elgatito/script.elementum.burst#35] opened 2018-03-23 22:30 UTC
Hello!

I'm trying to create a provider for TNTVillage (a pretty reliable torrent site in Italy).
I definitely need some help. First issue for me is that it uses XMLHttp POST request to search for result.

Once we get the results page, it should be pretty easy, as it is just a table to parse.
Here is the site: http://www.tntvillage.scambioetico.org/?releaselist

Can someone help bootstrap the provider? I'm trying to add it to provider.json.
Thanks.

**Comment by kalika303** [comment] 2018-04-09 18:36
Is there any other provider with POST requests that I can take as reference?
Thanks.

**Comment by rik91** [comment] 2018-04-11 05:12
It seems that there is no parameter for post request in search engine, except for authentification request. :-(
And in provider.json, I don't see any other providers which do that...

Possible enhancement ?

**Comment by elgatito** [comment] 2018-04-11 05:15
Possible, but currently not implemented. Needs proper post data submission and generation.

**Comment by mancuniancol** [comment] 2018-04-14 11:28
The implementation is there, but it is not well documented.  
Just add:
"post_data" : "{'cat': '0', 'page': '1', 'srcrel': 'QUERY'}",
to the definition json of the provider

**Comment by mancuniancol** [comment] 2018-04-21 11:03
No, it is not. Even you base_url is incomplete.  :(

**Comment by mancuniancol** [comment] 2018-04-21 11:04
I have the right one in my fork.  I need to do different pull requests to be integrated here.

**Comment by witsche** [comment] 2018-04-23 06:52
@mancuniancol please, can you share your json here?

thanks

**Comment by LinearLambda** [comment] 2018-05-27 17:35
For italian users this feature will transform Elementun into the best addon ever, please add TNT as provider!

**Comment by elgatito** [comment] 2018-06-25 07:37
Please, try with Burst v0.0.18. 
TNTVillage added and looks good for searching.
Send kudo's to @mancuniancol

**Comment by LinearLambda** [comment] 2018-06-26 12:09
Yesterday i tried Burst v0.0.18, i don't understand if is already working or not but from my side is just showing random torrent with no correlation with search text.

**Comment by witsche** [comment] 2018-06-26 12:16
for me, like LinearLambda, is the same: no correlation between search text and showed torrent

but I switched on TNTVillage provide and switched off any other provider

**Comment by abioneperhobby** [comment] 2018-06-29 21:29
Aspected results 
![screenshot_20180629-232834_chrome](https://user-images.githubusercontent.com/2149815/42115685-32f0fb5e-7bf4-11e8-9a7c-3b35b255d5c7.jpg)

**Comment by abioneperhobby** [comment] 2018-07-02 08:19
@kalika303 i don't use http://www.tntvillage.scambioetico.org/src/releaselist.php , i use http://www.tntvillage.scambioetico.org/?releaselist but i see that http://www.tntvillage.scambioetico.org/?releaselist calls http://www.tntvillage.scambioetico.org/src/releaselist.php with post  form data parameter, for example

http://www.tntvillage.scambioetico.org/src/releaselist.php
```
cat: 0
page: 1
srcrel: the 100
```
this returns the same table you mentioned, but with the same result.
due the provider is passing the right parameters,
![image](https://user-images.githubusercontent.com/2149815/42152725-57ce92f8-7de1-11e8-8a98-fc13d103355b.png)
i think the problem is on the scraper

**Comment by elgatito** [comment] 2018-07-02 08:31
I will make a fix on the next week, not earlier.

**Comment by elgatito** [comment] 2018-07-12 13:34
Will be fixed in the next version. As well as iscorsanero.

**Comment by elgatito** [comment] 2018-07-12 13:46
Please, try v0.0.19

**Comment by abioneperhobby** [comment] 2018-07-16 14:57
@elgatito tntvillage works, thanks.
i have to test corsaronero

**Comment by LinearLambda** [comment] 2018-07-16 15:30
Dear all,

TNT works, for long search text you need to increase the delay time to don't be timed out.

I want to say thanks you very much for your work @elgatito and all the other users that contribute to improve elementum.

**Comment by elgatito** [comment] 2018-07-18 08:36
@LinearLambda @abioneperhobby great. 

Feel free to submit proposal for adding more trackers.

**Closed by elgatito** 2018-07-18 08:36 UTC
